### ISSUE TITLE
0.4.6.0 does not seem to work with Cake 0.22.2

### ISSUE THREAD

**Issue by foxy1982** [SharpeRAD/Cake.AWS.S3#13]
I get the following error:
`Error: The assembly 'Cake.AWS.S3, Version=0.4.6.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.17.0).
This assembly need to reference at least Cake.Core version 0.22.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
envrionment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)`

**Comment by SharpeRAD** [comment]
For the time being either skip verification as indicated in the error message or pin Cake to a lower version as explained on their blog.

**Comment by SharpeRAD** [comment]
Fixed in v0.5.0
