### ISSUE TITLE
No multi-part upload

### ISSUE THREAD

**Issue by richardgavel** [SharpeRAD/Cake.AWS.S3#15]
The comments for uploading mention utilization of the multi-part upload capability, but no usage of the defined AWS SDK API (https://docs.aws.amazon.com/AmazonS3/latest/dev/HLuploadFileDotNet.html?shortFooter=true) is seen in the code that I can find.

**Comment by SharpeRAD** [comment]
Then you didn't look [that hard](https://github.com/SharpeRAD/Cake.AWS.S3/blob/master/src/Cake.AWS.S3/Manager/S3Manager.cs#L913) 😄
