### ISSUE TITLE
Support S3 Transfer Acceleration

### ISSUE THREAD

**Issue by richardgavel** [SharpeRAD/Cake.AWS.S3#21]
Add support for transfer acceleration, which would just involve adding a property to the UploadSettings and applying it when creating the S3 client.

https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration-examples.html#transfer-acceleration-examples-dotnet

**Comment by SharpeRAD** [comment]
Added Accelerate property to S3Settings in v0.6.6

**Comment by SharpeRAD** [comment]
👍
