### ISSUE TITLE
0.6.7 package is missing dependencies

### ISSUE THREAD

**Issue by ocean-orrick** [SharpeRAD/Cake.AWS.S3#26]
In 0.6.6, along with Cake.AWS.S3.dll the following dependencies were included in the lib/ folder:

AWSSDK.S3.dll
AWSSDK.Core.dll
MimeTypesMap.dll

In 0.6.7 the only library present is Cake.AWS.S3.dll and cake script now immediately fails with the following errors:

```
Could not load [repo]\tools\Addins\Cake.AWS.S3.0.6.7\lib\net46\Cake.AWS.S3.dll (missing AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604)
error CS1061: 'ICakeContext' does not contain a definition for 'CreateDownloadSettings' and no extension method 'CreateDownloadSettings' accepting a first argument of type 'ICakeContext' could be found (are you missing a using directive or an assembly reference?)
error CS0103: The name 'S3Download' does not exist in the current context
```

**Comment by ocean-orrick** [comment]
I see that the missing libraries are referenced as dependencies in the nuspec, so it seems that the actual bug of this issue may be Cake not properly pulling in nuget dependencies from addins (not sure if that's an expected behavior for them or not). Assuming that a fix should come from their end, in the meantime to avoid breaking stuff, I would suggest readding those dlls to the files list of the nuspec

**Comment by SharpeRAD** [comment]
Hi Sean thanks for raising the issue, it looks like @gitfool [commit](https://github.com/SharpeRAD/Cake.AWS.S3/commit/517c7bc8074f70c0fa5aea8c2dfaa8286dc09d6d#diff-36bbd9a502cc60a7311f36456e017ddc) removed these dependencies.

A work around would be to use `#addin "Cake.AWS.S3&loaddependencies=true"` but im not sure if thats the right aproach so I've deployed another version **Cake.AWS.S3 v0.6.8** that adds the net46 dependencies back.

**Comment by gitfool** [comment]
I removed them because it's not a good idea to embed your NuGet dependencies.

If you add them back then you also need to add the .NET Standard 2.0 ones!

**Comment by SharpeRAD** [comment]
In general Nuspec terms (IE: Not within the context of a Cake addin) I totally agree with you but Cakes default is not to import net46 dependencies so you're introducing a breaking change without a warning. 

Im not really sure what the recommended Cake addin best practices are for this so happy for anyone to point me to the best approach. Having to specify the load dependencies flag feels wrong to me.

**Comment by ocean-orrick** [comment]
Agree that it's not a good idea to embed your nuget dependencies but it seems that Cake doesn't actually look at them by default. 

I tried doing `Cake.AWS.S3&version=0.6.7&loaddependencies=true` and that did work though I'm not really sure why Cake seems to default to loaddependencies=false. 

Shared this issue over in the Cake gitter.im channel and hoping to get some explanation of why that is and what the recommended right approach would be.

**Comment by gitfool** [comment]
Linking the [answer ](https://gitter.im/cake-build/cake?at=5cc789a18790b0307e2419ca) for reference.
