### ISSUE TITLE
Uploading file with Headers - appears to not work

### ISSUE THREAD

**Issue by rluiten** [SharpeRAD/Cake.AWS.S3#29]
versions Cake 0.32.1
versions Cake.AWS.S3 0.6.8
Operating system I am on Windows 10.

The file uploads fine, but the headers appear to not be getting set.

It may be that I am missing something, however I am not seeing it would appreciate any guidance.

The file is just a index.html.

Here is the relevant part of my cake script.
```csharp
    var sync = new SyncSettings()
    {
        AccessKey = accessKey,
        SecretKey = secretKey,
        BucketName = bucketName,
        CannedACL = S3CannedACL.PublicRead,
        CompressContent = true,
        DefaultContentType = "text/html",
        GenerateContentType = true,
        Region = RegionEndpoint.APSoutheast2,
    };
    sync.Headers.CacheControl = "private, no-cache, no-store, proxy-revalidate, no-transform";
    sync.Headers["Pragma"] = "no-cache";
    await S3SyncUpload(file, sync);
```

**Comment by SharpeRAD** [comment]
This project is just a wrapper for AWS .Net, any validation of headers will occur in their library or on AWS server side. I have had issues with setting headers in the past, so while your header may be technically correct regarding the spec don't assume that AWS supports every option. 

I would start by removing **Pragma**, including **max-age** in the **Cache-Control** header and simplifying the list of options until you find the combination that AWS does not support.

**Comment by rluiten** [comment]
I've tried only setting max-age for cache control and nothing else 

`sync.Headers.CacheControl = "max-age=100";`

Still doesn't work for me.
So I have switched to using `aws s3 cp` and setting cache control headers for the file I need it on.
Called using StartProcess, this is setting the metdata for m
