### ISSUE TITLE
AWS environment variables and fallback credentials

### ISSUE THREAD

**Issue by gitfool** [SharpeRAD/Cake.AWS.S3#4]
This is a very useful addin for Cake, thanks! :wink: 

One problem I hit was that the AWS environment variables used by CakeEnvironmentExtensions don't match what's used by the AWS SDK:
- [CakeEnvironmentExtensions.cs#L31](https://github.com/SharpeRAD/Cake.AWS.S3/blob/master/src/S3/Extensions/Context/CakeEnvironmentExtensions.cs#L31)
- [AWSCredentials.cs#L649](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/AWSCredentials.cs#L649)

Was this a deliberate choice to differentiate them from the fallback credentials used by the SDK?

Normally I use the ctors which leverage the FallbackCredentialsFactory:
- [AmazonS3Client.cs#L60](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Generated/_bcl45/AmazonS3Client.cs#L60)
- [AmazonS3Client.cs#L79](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Generated/_bcl45/AmazonS3Client.cs#L79)

... which gives you a few ways to automatically inject the credentials - via an instance profile when running inside AWS or via the standard environment variables when running outside AWS.

Not a major problem obviously, but it does require more setup than expected for the common case, so this addin should ideally use the same standard conventions already established by the AWS SDK.

**Comment by SharpeRAD** [comment]
Sorry for the delay in replying I was out of the country with limited access to the internet. I can't argue with your logic so I've updated all of my AWS addins to use the SDK naming convention :smile:

**Comment by gitfool** [comment]
Thanks @SharpeRAD.

FWIW, here is [FallbackCredentialsFactory](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/AWSCredentials.cs#L1204) which has more flexible options for specifying AWS credentials, including via environment variables or instance profiles, the latter of which is the recommended approach when running from _inside_ AWS. I don't need this right now, but I'm sure others will be doing builds on EC2 instances...

In order to leverage this you'd need to use the other ctors for any Amazon clients, although I just noticed that FallbackCredentialsFactory is public, so another way might be to call [FallbackCredentialsFactory.GetCredentials()](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/AWSCredentials.cs#L1228) directly if you need more control?
